# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

name: Deploy Azure VM w/ disks

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'AzureDevOps'
  resourceGroupName: 'rg-theta-vm-01'
  location: 'australia-east'
  diskTemplateFile: './disks/disk.bicep'
  watcherTemplateFile: './virtualMachines/azureNetworkWatcher.bicep'
  diagTemplateFile: './virtualMachines/vmDiagnostics.bicep'
  vmTemplateFile: './virtualMachines/vm.bicep'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create OS Disk'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(diskTemplateFile)'
    overrideParameters: '-name OSDisk -sku StandardHDD_LRS -diskSizeGB 127 -diskIOPSReadWrite 500 -diskMBpsReadWrite 60'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create Disk 0'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(diskTemplateFile)'
    overrideParameters: '-name SSD-SQLData -sku StandardSSD_LRS -diskSizeGB 256 -diskIOPSReadWrite 500 -diskMBpsReadWrite 60'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create Disk 1'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(diskTemplateFile)'
    overrideParameters: '-name SSD-SQLLog -sku StandardSSD_LRS -diskSizeGB 256 -diskIOPSReadWrite 500 -diskMBpsReadWrite 60'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create VM'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(vmTemplateFile)'
    overrideParameters: '-adminUsername headet -adminPassword $(adminPassword) -vmSize Standard_A8m_v2 -vmName thetabcsync -nicName thetabcsync464 -storageAccountName thetabcsyncdiag -diskOsName OSDisk -disk0Name SSD-SQLData -disk1Name SSD-SQLLog'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create Network Watcher'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(watcherTemplateFile)'
    overrideParameters: '-vmName thetabcsync'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Create Vm Diagnostics'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(azureServiceConnection)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(diagTemplateFile)'
    overrideParameters: '-vmName thetabcsync -storageAccountName 123 -storageAccountKey 123 -storageAccountEndpoint 123 -xmlCfg 123'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'